# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Telemetrix and Telemetrix-AIO User's Guide
repo_url: https://github.com/MrYsLab/telemetrix
copyright: > # should remain a link to the original theme
  Copyright &copy; 2020-2023 Alan Yorinks &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Last 
  Modified: October 23, 2023

nav:
    - Introduction: index.md
    - What Is Contained In This Guide?: contents.md
    - System and Installation Requirements:
          - Verifying Python 3 Version: python_3_verify.md
          - Python 3 Installation: python_install.md
          - Installing Telemetrix: install_telemetrix.md
          - Installing Telemetrix-AIO: install_telemetrix-aio.md
          - Installing Telemetrix4Arduino: telemetrix4arduino.md
          - Installing And Using Telemetrix4Esp8266: telemetrix4esp8266.md
          - Upgrading To The Latest Version Python Clients: upgrade.md
    - Specifying Pin Numbers: pins.md
    - The Python APIs:
        - The __init__ Method: init.md
        - Setting Pin Modes: pin_modes.md
        - Enabling/Disabling Analog, Digital, and SONAR Reporting: enable_disable.md
        - Writing Values To Pins And Selected Devices:  device_writes.md
        - I2C Reads And Writes: i2c.md
        - OneWire Commands: onewire.md
        - SPI Commands: spi.md
        - Stepper Commands: stepper.md
        - Shutting Down: management.md
        - Debugging: debug.md
    - About: about.md
    - License: license.md
# theme: windmill

theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer