site_name: Telemetrix and Telemtrix-AIO User's Guide
nav:
    - Introduction: index.md
    - What Is Contained In This Guide?: contents.md
    - System and Installation Requirements:
          - Verifying Python 3 Version: python_3_verify.md
          - Python 3 Installation: python_install.md
          - Installing Telemetrix: install_telemetrix.md
          - Installing Telemetrix-AIO: install_telemetrix-aio.md
          - Installing Telemetrix4Arduino: telemetrix4arduino.md
          - Upgrading To The Latest Version Python Clients: upgrade.md
    - The Python APIs:
        - The __init__ Method: init.md
        - Setting Pin Modes: pin_modes.md
        - Enabling/Disabling Analog And Digital Reporting: enable_disable.md
        - Writing Values To Pins And Selected Devices:  device_writes.md
        - I2C Reads And Writes: i2c.md
        - Shutting Down: management.md
        - Debugging: debug.md
    - Extentending Telemetrix: dht.md
    - About: about.md
    - License: license.md
# theme: windmill

theme:
  name: 'material'
